### ISSUE TITLE
bbb: set default resolution to low

### ISSUE THREAD

**Issue by sebastianfischer** [stadtulm/a13-ansible#1]
set default video resolution to low 100

add documentation for teachers how to set high quality for their own webcam

see https://docs.bigbluebutton.org/2.2/customize.html#reduce-bandwidth-from-webcams

**Comment by robbi5** [comment]
with https://github.com/n0emis/ansible-role-bigbluebutton/pull/14 configuration manipulation for meteor landed in the bbb role. we can use this \o/
