### ISSUE TITLE
greenlight: email Verifikation / pw Reset muss mehrmals ausgelöst werden 

### ISSUE THREAD

**Issue by sebastianfischer** [stadtulm/a13-ansible#3]
soweit wir das aus dem "Supportraum" sehen können haben die meisten Nutzer haben keine Probleme mit Nutzerverifikation / E-Mail Reset. Allerdings hatten ca. 20 - 30 Nutzer (grobe Schätzung) was ungefähr 10% der Nutzer entspricht das Problem, dass der erste Link für E-Mail Verifikation /  PW-Reset auf eine 404 Seite führt. Meist reicht die Anweisung die Verifikation / PW Reset noch mal auszulösen. 

Allerdings gabs auch solche Fälle. Chat Verlauf aus Rocket Chat 01. Mai ~18 Uhr:
>A: Guten Tag, ich hab seit mehreren Tagen das Problem, dass der Verifizierungslink auf die Fehlerseite führt. Habe auch schon nachgelesen und befolgt, was auf der Seite steht: Seite wieder verlassen, neu einloggen, etc. Es will nicht funktionieren.
>B: Hai, ging es auch nicht mit zuschicken-lassen eines neuen Verifizierungslinks? Bzw war das das „neu einloggen etc.“?
> A: Nein, habe mittlerweile schon vier oder fünf neue Links schicken lassen. kamen alle an aber gingen immer auf die Fehlerseite
> B: huch spannend. Ich schau mal, was ich machen kann, moment
> A: Danke
> B: ich hab nochmal einen haendischen Reset gemacht, es muesste nun eine Mail mit Aufforderung zum neu setzen des Passworts gekommen sein
> A: so, habe das neue passwort gesetzt. Jetzt einloggen und wieder einen Link anfordern?
> b: genau
> A: tab schließen? oder egal?
> B: hmm sollt eigentlich keinen unterschied machen
> A: perfekt. hat funktioniert. vielen Dank!!! Auch dass so schnell reagiert wird. top!

**Comment by sebastianfischer** [comment]
Evtl. Problem mit Setup von nginx / greenlight bzgl. CSRF?

> cat /var/log/syslog | grep "Can't verify CSRF token authenticity" | wc -l

ergibt 82 Einträge nur für heute (4. Mai) 

Mögliche Problemlösung?
```
location / {
    ....
    proxy_set_header X-Forwarded-Ssl on;
    ....
}
```
siehe: https://github.com/bigbluebutton/greenlight/issues/997#issuecomment-607093549

**Comment by robbi5** [comment]
Dafür haben wir eigentlich `proxy_set_header    X-Forwarded-Proto $scheme;` drin, mal forschen warum das nicht tut.

**Comment by sebastianfischer** [comment]
Anscheinend hat Release 2.5.5 von greenlight https://github.com/bigbluebutton/greenlight/releases/tag/release-2.5.5 doch Besserung gebracht, seit einer Woche keine neuen Meldungen wegen Registrierungen / Passwort reset
